<a href="https://colab.research.google.com/github/Huong1703/Homework/blob/main/Week5_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Viết chương trình người dùng nhập vào 2 mảng 2 chiều có cùng kích thước (với điều kiện không có số 0) Thực hiện các phép toán cộng, trừ, nhân, chia các phần tử của 2 mảng đó.

- Tính tổng các phần tử theo cột của mảng cuối cùng. (np.sum)
- Tính tích các phần tử theo hàng của mảng cuối cùng. (np.prod)

In [ ]:
import numpy as np

def main():
    rows = int(input("Nhập số hàng: "))
    cols = int(input("Nhập số cột: "))

    print("Nhập mảng thứ nhất:")
    array1 = get_input_array(rows, cols)

    print("Nhập mảng thứ hai:")
    array2 = get_input_array(rows, cols)

    add_result = np.add(array1, array2)
    subtract_result = np.subtract(array1, array2)
    multiply_result = np.multiply(array1, array2)
    divide_result = np.divide(array1, array2, where=array2!=0)

    print("Kết quả")
    print("Cộng:")
    print(add_result)
    print("Trừ:")
    print(subtract_result)
    print("Nhân:")
    print(multiply_result)
    print("Chia:")
    print(divide_result)

    column_sum = np.sum(divide_result, axis=0)
    print("\nTổng theo cột của mảng cuối cùng:")
    print(column_sum)

    row_product = np.prod(divide_result, axis=1)
    print("\nTích theo hàng của mảng cuối cùng:")
    print(row_product)

def get_input_array(rows, cols):
    array = np.empty((rows, cols), dtype=float)
    for i in range(rows):
        for j in range(cols):
            array[i, j] = float(input(f"Nhập phần tử [{i}][{j}]: "))
    return array
main()


Nhập số hàng: 2
Nhập số cột: 3
Nhập mảng thứ nhất:
Nhập phần tử [0][0]: 4
Nhập phần tử [0][1]: 0
Nhập phần tử [0][2]: 2
Nhập phần tử [1][0]: 3
Nhập phần tử [1][1]: 4
Nhập phần tử [1][2]: 8
Nhập mảng thứ hai:
Nhập phần tử [0][0]: 6
Nhập phần tử [0][1]: 7
Nhập phần tử [0][2]: 5
Nhập phần tử [1][0]: 3
Nhập phần tử [1][1]: 4
Nhập phần tử [1][2]: 8

Kết quả của các phép toán:
Cộng:
[[10.  7.  7.]
 [ 6.  8. 16.]]

Trừ:
[[-2. -7. -3.]
 [ 0.  0.  0.]]

Nhân:
[[24.  0. 10.]
 [ 9. 16. 64.]]

Chia:
[[0.66666667 0.         0.4       ]
 [1.         1.         1.        ]]

Tổng theo cột của mảng cuối cùng:
[1.66666667 1.         1.4       ]

Tích theo hàng của mảng cuối cùng:
[0. 1.]


Bài tập ma trận

In [ ]:
import numpy as np
A = np.array([[10, 1, 2],
             [9, 7, 4],
             [0, 2, 1]])
B = np.array([[2, 3, 4],
             [0, 4, 2],
             [3, 2, 1]])

In [ ]:
result = np.dot(A, B)

print("Tích của hai ma trận A và B:")
print(result)

Tích của hai ma trận A và B:
[[26 38 44]
 [30 63 54]
 [ 3 10  5]]


In [ ]:
A_transpose = A.T

BA_transpose = np.dot(B, A_transpose)
AB_transpose = np.dot(A_transpose, B)

result = np.dot(BA_transpose, AB_transpose)

print("BA^TAB^T:")
print(result)

BA^TAB^T:
[[1130 4211 3068]
 [ 518 2028 1354]
 [1075 3939 2957]]


In [ ]:
B_transpose = B.T

AB_transpose = np.dot(A, B_transpose)
BA_transpose = np.dot(B, A.T)

result = np.dot(AB_transpose, BA_transpose)

print("AB^TBA^T:")
print(result)

AB^TBA^T:
[[2181 3523  560]
 [3523 6346 1135]
 [ 560 1135  225]]


In [ ]:
def softmax(matrix):
    exp_matrix = np.exp(matrix)
    return exp_matrix / np.sum(exp_matrix, axis=1, keepdims=True)

A = np.array([[10, 1, 2],
              [9, 7, 4],
              [0, 2, 1]])

softmax_result = softmax(A)

print("Phân phối xác suất sau khi đi qua hàm softmax:")
print(softmax_result)

Phân phối xác suất sau khi đi qua hàm softmax:
[[9.99541338e-01 1.23353201e-04 3.35308764e-04]
 [8.75600595e-01 1.18499655e-01 5.89975040e-03]
 [9.00305732e-02 6.65240956e-01 2.44728471e-01]]


In [ ]:
predicted_labels = np.argmax(softmax_result, axis=1)

print("Nhãn dự báo cho mỗi dòng:")
print(predicted_labels)

Nhãn dự báo cho mỗi dòng:
[0 0 1]


In [ ]:
sum_per_row = np.sum(A, axis=1)
mean_per_row = np.mean(A, axis=1)
min_per_row = np.min(A, axis=1)
max_per_row = np.max(A, axis=1)

print("Tổng", sum_per_row)
print("TB", mean_per_row)
print("GTNN", min_per_row)
print("GTLN", max_per_row)

Tổng [13 20  3]
TB [4.33333333 6.66666667 1.        ]
GTNN [1 4 0]
GTLN [10  9  2]


Bài tập với file excel

In [ ]:
## Kết nối google drive và google collab
from google.colab import drive

drive.mount("/content/drive")


Mounted at /content/drive


In [ ]:
## Gọi ra những thư viện cần thiết
import numpy as np
import pandas as pd

In [ ]:
## Đọc file data từ google drive
dataset = pd.read_excel("/content/drive/MyDrive/Week4-data_06.xlsx")
print(dataset)
print(dataset.head())

                     Tên  Mã số               Trường cấp 2  Nguyện vọng 1  \
0           QUÁCH KIM HÀ  60132             THCS Phú Cường              6   
1       PHẠM TRÚC PHƯƠNG  60421        THCS Trần Đại Nghĩa              6   
2         TRẦN KHẢ DOANH  60075    THCS-THPT Nguyễn Khuyến              6   
3      NGUYỄN MAI PHƯƠNG  60417        THCS Trần Đại Nghĩa              6   
4          TRẦN MINH THY  60558  THCS Nguyễn Thị Minh Khai              6   
..                   ...    ...                        ...            ...   
636        TRẦN NHẬT ANH  60032       THCS Nguyễn Văn Tiết              6   
637  DOÃN THỊ PHƯƠNG ANH  60017            THCS Bình Chiểu              6   
638       CÙ THỊ GIA HÂN  60151     THCS Nguyễn Trung Trực              6   
639      NGUYỄN TƯỜNG VY  60622        THCS Trịnh Hoài Đức              6   
640         LƯU QUANG ĐÔ  60108        THCS Trịnh Hoài Đức              6   

     Nguyện vọng 2  Điểm cộng   Văn   Anh  Toán   Tổng  Xếp hạng  
0       

In [ ]:
data = dataset.to_numpy()
print(data.shape)

(641, 11)


In [ ]:
print(data[0])

['QUÁCH KIM HÀ' 60132 'THCS Phú Cường' 6 2.0 3.0 9.0 8.9 8.75 29.65 1]


In [ ]:
print(data.dtype)

object


In [ ]:
print(data[0].dtype)

object


In [ ]:
np.nan_to_num([0.3, np.nan, 2.4])

array([0.3, 0. , 2.4])

In [ ]:
data[:, 5] = np.nan_to_num(data[:, 5].astype(float))
print(data[:, 5])
print(data[-1])

[3.0 2.0 2.0 0.0 2.0 0.0 2.0 0.0 0.0 2.0 2.0 0.0 1.0 0.0 0.0 2.0 2.0 1.0
 0.0 1.0 0.0 0.0 0.0 0.0 2.0 2.0 2.0 0.0 2.0 0.0 0.0 2.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 2.0 0.0 2.0 0.0 2.0 0.0 2.5 0.0 0.0 0.0 2.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
 1.0 0.0 2.0 0.0 1.0 0.0 1.0 2.0 0.0 0.0 0.0 0.0 0.0 2.0 0.0 2.0 1.0 0.0
 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 2.0 0.0 0.0 0.0 0.0 0.0 2.0 0.0
 0.0 1.0 0.0 0.0 0.0 0.0 1.0 1.0 1.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 2.0 0.0
 0.0 2.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0
 0.0 1.0 0.0 2.0 0.0 0.0 0.0 2.0 2.0 1.0 1.0 0.0 0.0 0.0 0.0 2.0 0.0 0.0
 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 2.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0
 2.0 0.0 2.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 1.0 2.0 0.0 0.0 0.0 0.0 2.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0
 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
 1.0 1.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.

In [ ]:
## Đưa ra thông tin của bạn với mã số: 60457
ma_so_can_tim = 60457
thong_tin_hs = dataset[dataset['Mã số'] == ma_so_can_tim]
print("Thông tin của học sinh có mã số", ma_so_can_tim, ":\n", thong_tin_hs)


Thông tin của học sinh có mã số 60457 :
                       Tên  Mã số   Trường cấp 2  Nguyện vọng 1  Nguyện vọng 2  \
100  NGUYỄN LÊ PHƯƠNG TÂM  60457  THCS Phú Long              6            7.0   

     Điểm cộng  Văn  Anh  Toán   Tổng  Xếp hạng  
100        2.0  7.0  9.4  6.25  24.65       101  


In [ ]:
## Đưa ra thông tin của bạn với tên là: Nguyễn Đình Nhân
ten_can_tim = "Nguyễn Đình Nhân"
thong_tin_hs = dataset[dataset['Tên'] == ten_can_tim]
print("Thông tin của học sinh có tên", ten_can_tim, ":\n", thong_tin_hs)

Thông tin của học sinh có tên Nguyễn Đình Nhân :
 Empty DataFrame
Columns: [Tên, Mã số, Trường cấp 2, Nguyện vọng 1, Nguyện vọng 2, Điểm cộng, Văn, Anh, Toán, Tổng, Xếp hạng]
Index: []


In [ ]:
## Đưa ra thông tin của các bạn từ mã số: 60004 đến  60200 (Bạn nào không có thì không cần đưa ra)
tu = 60004
den = 60200
thong_tin_hs = dataset[(dataset['Mã số'] >= tu) & (dataset['Mã số'] <= den)]
print("thông tin của các bạn từ mã số: 60004 đến  60200 (Bạn nào không có thì không cần đưa ra)", thong_tin_hs)

thông tin của các bạn từ mã số: 60004 đến  60200 (Bạn nào không có thì không cần đưa ra)                      Tên  Mã số               Trường cấp 2  Nguyện vọng 1  \
0           QUÁCH KIM HÀ  60132             THCS Phú Cường              6   
2         TRẦN KHẢ DOANH  60075    THCS-THPT Nguyễn Khuyến              6   
5     PHẠM LỢI NGỌC HIỀN  60158         THCS Châu Văn Liêm              6   
7         ĐẶNG MINH CHÂU  60067  THCS Nguyễn Thị Minh Khai              6   
10         NGÔ MỸ GIA AN  60004    THCS-THPT Nguyễn Khuyến              6   
..                   ...    ...                        ...            ...   
634      NGUYỄN TUẤN ANH  60033            THCS Thanh Bình              6   
636        TRẦN NHẬT ANH  60032       THCS Nguyễn Văn Tiết              6   
637  DOÃN THỊ PHƯƠNG ANH  60017            THCS Bình Chiểu              6   
638       CÙ THỊ GIA HÂN  60151     THCS Nguyễn Trung Trực              6   
640         LƯU QUANG ĐÔ  60108        THCS Trịnh Hoài Đức      

In [ ]:
## Tính điểm thi trung bình cho từng bạn sinh viên
dataset['ĐTB'] = dataset[['Văn', 'Anh', 'Toán']].mean(axis=1)
print("điểm thi trung bình cho từng bạn sinh viên:\n", dataset[['Tên', 'Điểm Trung Bình']])

Thông tin của các bạn sinh viên với điểm trung bình:
                      Tên  Điểm Trung Bình
0           QUÁCH KIM HÀ         8.883333
1       PHẠM TRÚC PHƯƠNG         9.200000
2         TRẦN KHẢ DOANH         9.033333
3      NGUYỄN MAI PHƯƠNG         9.333333
4          TRẦN MINH THY         8.650000
..                   ...              ...
636        TRẦN NHẬT ANH         4.466667
637  DOÃN THỊ PHƯƠNG ANH         4.450000
638       CÙ THỊ GIA HÂN         4.250000
639      NGUYỄN TƯỜNG VY         4.150000
640         LƯU QUANG ĐÔ         3.883333

[641 rows x 2 columns]


In [ ]:
## Tính điểm thi trung bình theo từng môn cho toàn bộ sinh viên
diem_tb_mon = dataset[['Văn', 'Anh', 'Toán']].mean()
print("điểm thi trung bình theo từng môn cho toàn bộ sinh viên:\n", diem_tb_mon)

điểm thi trung bình theo từng môn cho toàn bộ sinh viên:
 Văn     7.287051
Anh     6.996256
Toán    7.108034
dtype: float64


In [ ]:
## Đưa ra điểm thi trung bình cao nhất và thấp nhất cho toàn bộ 3 môn.
diem_tb_cao_nhat = dataset['Điểm Trung Bình'].max()
diem_tb_thap_nhat = dataset['Điểm Trung Bình'].min()
print("Điểm trung bình cao nhất: ", diem_tb_cao_nhat)
print("Điểm trung bình thấp nhất: ", diem_tb_thap_nhat)

Điểm trung bình cao nhất:  9.333333333333334
Điểm trung bình thấp nhất:  3.8833333333333333


In [ ]:
## Xếp danh sách dựa vào điểm trung bình của môn Toán + Anh, tìm bạn có vị trí 100
dataset['Điểm Trung Bình Toán Anh'] = (dataset['Toán'] + dataset['Anh']) / 2
df_sorted = dataset.sort_values(by='Điểm Trung Bình Toán Anh', ascending=False)

vi_tri = 100
thong_tin_vi_tri_100 = df_sorted.iloc[vi_tri - 1]

print("Thông tin của bạn có vị trí", vi_tri, ":\n", thong_tin_vi_tri_100)

Thông tin của bạn có vị trí 100 :
 Tên                         NGUYỄN NGỌC QUỲNH ANH
Mã số                                       60010
Trường cấp 2                  THCS Trịnh Hoài Đức
Nguyện vọng 1                                   6
Nguyện vọng 2                                 8.0
Điểm cộng                                     2.0
Văn                                           7.5
Anh                                           9.8
Toán                                         6.75
Tổng                                        26.05
Xếp hạng                                       41
Điểm Trung Bình                          8.016667
ĐTB                                      8.016667
Điểm Trung Bình Toán Anh                    8.275
Name: 40, dtype: object


In [ ]:
## Giả sử 1 trường lấy toàn bộ 300 sinh viên, dựa theo

In [ ]:
## a) Điểm môn Toán từ cao xuống thấp
df_sorted_toan = dataset.sort_values(by='Toán', ascending=False)

so_sinh_vien = 300
df_top300_toan = df_sorted_toan.head(so_sinh_vien)

print("300 sinh viên, dựa theo Điểm môn Toán từ cao xuống thấp :\n", df_top300_toan)

300 sinh viên, dựa theo Điểm môn Toán từ cao xuống thấp :
                             Tên  Mã số               Trường cấp 2  \
8                  LÊ MINH NGỌC  60334        THCS Trần Đại Nghĩa   
23                PHẠM THANH HÀ  60129  THCS Nguyễn Thị Minh Khai   
20                  LƯU MINH ÂN  60037        THCS Trần Đại Nghĩa   
5            PHẠM LỢI NGỌC HIỀN  60158         THCS Châu Văn Liêm   
11               NGUYỄN AN HOÀI  60169    THCS-THPT Nguyễn Khuyến   
..                          ...    ...                        ...   
346    NGUYỄN HUYỀN PHƯƠNG THẢO  60504          THCS Bình Thắng B   
166         BÙI MINH KHÁNH ĐOAN  60107            THCS Chu Văn An   
189  NGUYỄN TRƯỜNG THỤY ANH THƯ  60541        THCS Trịnh Hoài Đức   
162            PHẠM PHƯƠNG ĐÔNG  60109       THCS Nguyễn Văn Tiết   
342              MAI THANH BÌNH  60055        THCS Trịnh Hoài Đức   

     Nguyện vọng 1  Nguyện vọng 2  Điểm cộng   Văn   Anh  Toán   Tổng  \
8                6            7.0      

In [ ]:
## b) Điểm tổng 3 môn và điểm cộng từ cao xuống thấp
dataset['Tổng Điểm'] = dataset[['Văn', 'Anh', 'Toán']].sum(axis=1) + dataset['Điểm cộng']
df_sorted_tong_diem = dataset.sort_values(by=['Tổng Điểm', 'Điểm cộng'], ascending=[False, False])

so_sinh_vien = 300
df_top300_tong_diem = df_sorted_tong_diem.head(so_sinh_vien)

print("300 sinh viên, dựa theo Điểm tổng 3 môn và điểm cộng từ cao xuống thấp:\n", df_top300_tong_diem)

300 sinh viên, dựa theo Điểm tổng 3 môn và điểm cộng từ cao xuống thấp:
                         Tên  Mã số               Trường cấp 2  Nguyện vọng 1  \
0              QUÁCH KIM HÀ  60132             THCS Phú Cường              6   
1          PHẠM TRÚC PHƯƠNG  60421        THCS Trần Đại Nghĩa              6   
2            TRẦN KHẢ DOANH  60075    THCS-THPT Nguyễn Khuyến              6   
4             TRẦN MINH THY  60558  THCS Nguyễn Thị Minh Khai              6   
6    NGUYỄN NGỌC KHÁNH LINH  60249            THCS Thuận Giao              6   
..                      ...    ...                        ...            ...   
265         TRẦN THỊ CẨM VY  60610              THCS Phú Long              6   
267           ĐOÀN HẢI LINH  60253            THCS Thuận Giao              6   
268       NGUYỄN THÙY TRANG  60565      THCS Nguyễn Trường Tộ              6   
269    LÊ NGUYỄN BẢO KHUYÊN  60238     THCS Nguyễn Trung Trực              6   
271         PHAN LÊ ANH THƯ  60540         THCS

In [ ]:
## c) Điểm trung bình 3 môn từ cao xuống thấp
dataset['ĐTB 3 Môn'] = dataset[['Văn', 'Anh', 'Toán']].mean(axis=1)
df_sorted_tb_3_mon = dataset.sort_values(by='ĐTB 3 Môn', ascending=False)

so_sinh_vien = 300
df_top300_tb_3_mon = df_sorted_tb_3_mon.head(so_sinh_vien)

print("D300 sinh viên, dựa theo Điểm trung bình 3 môn từ cao xuống thấp:\n", df_top300_tb_3_mon)

D300 sinh viên, dựa theo Điểm trung bình 3 môn từ cao xuống thấp:
                       Tên  Mã số               Trường cấp 2  Nguyện vọng 1  \
3       NGUYỄN MAI PHƯƠNG  60417        THCS Trần Đại Nghĩa              6   
5      PHẠM LỢI NGỌC HIỀN  60158         THCS Châu Văn Liêm              6   
7          ĐẶNG MINH CHÂU  60067  THCS Nguyễn Thị Minh Khai              6   
8            LÊ MINH NGỌC  60334        THCS Trần Đại Nghĩa              6   
1        PHẠM TRÚC PHƯƠNG  60421        THCS Trần Đại Nghĩa              6   
..                    ...    ...                        ...            ...   
316     VŨ TRỊNH LINH NHI  60352              THCS Phú Long              6   
152      NGUYỄN THÁI LONG  60268              THCS Phú Long              6   
151  NGUYỄN THỊ THÙY TRÂM  60575        THCS Trịnh Hoài Đức              6   
317  NGUYỄN TRẦN HOÀNG VI  60603        THCS Trần Đại Nghĩa              6   
318    TRẦN TÔ THANH LIÊM  60245        THCS Trịnh Hoài Đức              6 

In [ ]:
## Đưa ra danh sách những bạn sinh viên được chọn vào trường đó.
df_sorted_tong_diem = dataset.sort_values(by=['Tổng Điểm', 'Điểm cộng'], ascending=[False, False])
so_sinh_vien_can_lay = 300
df_duoc_chon = df_sorted_tong_diem.head(so_sinh_vien_can_lay)

print("danh sách những bạn sinh viên được chọn vào trường:\n", df_duoc_chon)

danh sách những bạn sinh viên được chọn vào trường:
                         Tên  Mã số               Trường cấp 2  Nguyện vọng 1  \
0              QUÁCH KIM HÀ  60132             THCS Phú Cường              6   
1          PHẠM TRÚC PHƯƠNG  60421        THCS Trần Đại Nghĩa              6   
2            TRẦN KHẢ DOANH  60075    THCS-THPT Nguyễn Khuyến              6   
4             TRẦN MINH THY  60558  THCS Nguyễn Thị Minh Khai              6   
6    NGUYỄN NGỌC KHÁNH LINH  60249            THCS Thuận Giao              6   
..                      ...    ...                        ...            ...   
265         TRẦN THỊ CẨM VY  60610              THCS Phú Long              6   
267           ĐOÀN HẢI LINH  60253            THCS Thuận Giao              6   
268       NGUYỄN THÙY TRANG  60565      THCS Nguyễn Trường Tộ              6   
269    LÊ NGUYỄN BẢO KHUYÊN  60238     THCS Nguyễn Trung Trực              6   
271         PHAN LÊ ANH THƯ  60540         THCS Châu Văn Liêm      

In [ ]:
## So sánh 2 bạn sinh viên mã số: 60575 và 60602 dựa trên tổng điểm 3 môn (không tính điểm cộng)
ma_so1 = 60575
ma_so2 = 60602
diem_sv1 = dataset.loc[dataset['Mã số'] == ma_so1, ['Văn', 'Anh', 'Toán']].sum(axis=1).values[0]
diem_sv2 = dataset.loc[dataset['Mã số'] == ma_so2, ['Văn', 'Anh', 'Toán']].sum(axis=1).values[0]

if diem_sv1 > diem_sv2:
    print(f"sinh viên có mã số {ma_so1} có tổng điểm 3 môn cao hơn.")
elif diem_sv1 < diem_sv2:
    print(f"sinh viên có mã số {ma_so2} có tổng điểm 3 môn cao hơn.")
else:
    print(f"hai sinh viên có mã số {ma_so1} và {ma_so2} có tổng điểm 3 môn bằng nhau.")

sinh viên có mã số 60602 có tổng điểm 3 môn cao hơn.
